<a href="https://colab.research.google.com/github/AdityaSinghDevs/pytorch-learn/blob/main/learn/autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd

In [36]:
import torch

In [37]:
x = torch.tensor([12], dtype=torch.float32, requires_grad=True)
x

tensor([12.], requires_grad=True)

In [38]:
y  = x**2
y

tensor([144.], grad_fn=<PowBackward0>)

In [39]:
y.backward()
x.grad

tensor([24.])

# For more complex functions

In [40]:
# without autograd
import math

def dz_dx(x):
  return 2*x* math.cos(x**2)

dz_dx(3)

-5.466781571308061

In [41]:
# with autograd
x = torch.tensor(3.0 , requires_grad = True)

In [42]:
y = x**2

In [43]:
z = torch.sin(y)   # creating a basic trignometric fn

In [44]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [45]:
z.backward()
x.grad

tensor(-5.4668)

# Now for a NN

## perceptron diagram in register, but simple NN

## values
| CGPA(x) | Placement(y)  |
|:--------|:--------------|
| 6.7     |   0.0         |


##Linear Transformation -> z = w.x + b
## activation -> y_pred  = sigmoid(z)
## Loss -> L = [ y . ln(y_pred) + (1 - y) . ln(1-y_pred) ]

## Therefore manually calculating grad of w wrt L
### - grad of L wrt y_pred -> dL/dy_pred  =  (y_pred - y)/y_pred(1-y_pred)
### - grad of y_pred wrt to z -> dy_pred/dz y_pred(1-y_pred)
### - grad of z wrt w ->  dz/dw = x and dz/db = 1

In [46]:
#Inputs
x = torch.tensor(6.7) # Input value
y = torch.tensor(0.0) #True label (binary)

w = torch.tensor(1.0 ) #wt
b = torch.tensor(0.0) #bias

In [51]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8  # Small value to avoid log(0)
  prediction = torch.clamp(prediction, epsilon, 1 - epsilon)
  return -(target * torch .log(prediction) + (1 - target) * torch.log(1-prediction))

In [52]:
# forward pass
z = w * x + b #wted sum
y_pred = torch.sigmoid(z) # predicted probability

#computing loss
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7012)

In [53]:
# Derivatives (Already calculated values)
#1. dL/dy_pred : Loss wrt prediction
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

#2 dy_pred/dz : Pred (y_pred) wrt z (sigmpoid fn)
dy_pred_dz = y_pred*(1-y_pred)

#3. dz/dw and dz/db : z wrt w and b
dz_dw = x # dz/dw = x
dz_db = 1 # dz/db = 1 (bias directly contributes to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [54]:
print(f" Manual Grad of loss wrt w : {dL_dw}")
print(f" Manual Grad of loss wrt b : {dL_db}")

 Manual Grad of loss wrt w : 6.691762447357178
 Manual Grad of loss wrt b : 0.998770534992218


# USING AUTOGRAD NOW (MENTOS ZINDaGI)

In [ ]:
x = torch.tensor(6.7) # No grad required as wont be computed for z or y
y = torch.tensor(0.0)

In [ ]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True) # grads required here hence true