<a href="https://colab.research.google.com/github/AdityaSinghDevs/pytorch-learn/blob/main/learn/nn_and_optim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import torch
import torch.nn as nn

In [30]:
#create a class

class Model(nn.Module): #inherit

    def __init__(self, num_features): #num_features is no. of features coming as input

      super().__init__() #invoking parent class constructor
      self.linear = nn.Linear(num_features, 1) # linear NN, output is 1
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
     out = self.linear(features) # w.x + b
     out = self.sigmoid(out) # applying sigmoid

     return out


In [31]:
# create a dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass

model(features)
# model.forward(features) works too but pytorch allows this for eas of use
# forward pass is automatically triggered whenever the class is called


tensor([[0.5437],
        [0.4913],
        [0.4594],
        [0.5216],
        [0.5002],
        [0.5904],
        [0.4939],
        [0.4879],
        [0.4857],
        [0.5481]], grad_fn=<SigmoidBackward0>)

In [32]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4294,  0.3143, -0.3942, -0.1039, -0.0240]], requires_grad=True)

In [33]:
#show bias
model.linear.bias

Parameter containing:
tensor([-0.1499], requires_grad=True)

# To visualize

In [34]:
!pip install torchinfo
from torchinfo import summary

In [35]:
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### 6 Trainable params (5 + 1)

# NN with hidden layer
## 5 inputs 3 hidden layer neurons, 1 neuron in output layer

### 5 inputs to 3 hidden neurons = 5x3= 15 weights, and 3 biases
### 3 inputs to single neuron, 3 weights and 1 bias

## TOTAL PARAMS = 18 weights, 4 biases (22)
## Relu in hidden and sigmoid in output

In [37]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear_layer_1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear_layer_2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear_layer_1(features)
    out = self.relu(out)
    out = self.linear_layer_2(out)
    out = self.sigmoid(out)

    return out

features2 = torch.rand(10,5)
model2 = Model2(features2.shape[1])
model2(features2)

tensor([[0.3104],
        [0.3056],
        [0.3418],
        [0.3380],
        [0.3424],
        [0.3349],
        [0.3372],
        [0.3293],
        [0.3427],
        [0.3299]], grad_fn=<SigmoidBackward0>)

In [38]:
summary(model2, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential Container

In [40]:
class Model3(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid(),
       )

  def forward(self, features):
    # out = self.linear_layer_1(features)
    # out = self.relu(out)
    # out = self.linear_layer_2(out)
    # out = self.sigmoid(out)

    out = self.network(features)

    return out

features3 = torch.rand(10,5)
model3 = Model2(features3.shape[1])
model3(features3)

tensor([[0.3685],
        [0.3401],
        [0.3656],
        [0.3866],
        [0.3868],
        [0.3606],
        [0.4145],
        [0.3302],
        [0.3897],
        [0.3726]], grad_fn=<SigmoidBackward0>)

# AGAIN USING BREAST CANCER DATASET

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

In [ ]:
df.drop(columns = ['id', 'Unnamed: 32'], inplace = True) #no need to use identity or unnamed

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)