<a href="https://colab.research.google.com/github/AdityaSinghDevs/pytorch-learn/blob/main/learn/Pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.9.0+cu126'

In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Tesla T4


## Creating a tensor

In [3]:
# using empty

a = torch.empty(2,3)
#created a shape, showing the valuesalready present in in that space created

type(a)

torch.Tensor

In [4]:
# using zeroes

b = torch.zeros(2,3)
b

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# using random
torch.rand(2,3)

tensor([[0.1606, 0.3847, 0.8268],
        [0.5725, 0.5855, 0.0782]])

In [7]:
# use of seed (to define a seed for reproducibility in rand)

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
# using tensor (custom tensor)
torch.tensor([[2,3],[4,5]])

tensor([[2, 3],
        [4, 5]])

In [9]:
# other ways
#arange -> provide a range
range = torch.arange(0,10,2)

#linspace -> a range linearly spaced
linspace = torch.linspace(0,10,10)

#using eye -> identity matrix
identity = torch.eye(3,3)

# using full -> a fully filled matrix with a specific value
full = torch.full((2,3),3)

print(range)
print(linspace)
print(identity)
print(full)


tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[3, 3, 3],
        [3, 3, 3]])


## Tensor shapes

In [10]:
# use python .shape attribute
x = torch.tensor([[2,3],[4,5]])
x.shape

torch.Size([2, 2])

In [11]:
# reproducing a shape
torch.empty_like(x)
torch.zeros_like(x)
torch.ones_like(x)
# torch.rand_like(x) #wont work as it generates float, and original matrix was int

tensor([[1, 1],
        [1, 1]])

## Tensor data types


In [12]:
# finding dtype
x.dtype

torch.int64

In [13]:
# assigning dtype

torch.tensor([1,2], dtype=torch.float64)

tensor([1., 2.], dtype=torch.float64)

In [14]:
y= x.to(torch.float32)

In [15]:
torch.rand_like(y)
torch.rand_like(x, dtype=torch.float32)

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

## Mathematical operations

In [16]:
# Scalar
y= torch.tensor([1,2])

y+2
y-2
y*2
y/2
y//3
y**2


tensor([1, 4])

In [17]:
# Element wise operations

a = torch.tensor([2,3])
b = torch.tensor([4,5])

a+b
a-b
a*b
a/b

tensor([0.5000, 0.6000])

In [18]:
c = torch.tensor([1,-3,4,5])
torch.abs(c) #absolute mod value
torch.neg(c) #ngative values
torch.exp(c) #exponent
torch.log(c) #logarithm
torch.round(c)
torch.ceil(c) #round up
torch.floor(c) #round down

tensor([ 1, -3,  4,  5])

In [19]:
torch.clamp(c, min=2, max=4) #to force numbers inside a range

tensor([2, 2, 4, 4])

In [20]:
# Reduction operations
e = torch.randint(size=(2,3), low =0 , high=4, dtype=torch.float32)
e

tensor([[2., 2., 1.],
        [0., 0., 3.]])

In [21]:
torch.sum(e)

#sum alog cols
torch.sum(e, dim=0)

#sum alog rows
torch.sum(e, dim=1)

tensor([5., 3.])

In [22]:
# mean
torch.mean(e)

#along col
torch.mean(e, dim=0)

#along row
torch.mean(e, dim=1)

tensor([1.6667, 1.0000])

In [23]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [24]:
# standard deviation
torch.std(e)

tensor(1.2111)

In [25]:
# product
torch.prod(e)

tensor(0.)

In [26]:
# argmax
torch.argmax(e) # max values position

#argmin
torch.argmin(e)

tensor(3)

In [27]:
#matrix operations

f = torch.tensor([[2,3], [5,6]])
g = torch.tensor([[1,2], [3,4]])

In [28]:
# matrix multiplication
torch.matmul(f,g)

tensor([[11, 16],
        [23, 34]])

In [29]:
# dot product
vec1 = torch.tensor([2,3])
vec2 = torch.tensor([4,5])
torch.dot(vec1,vec2) #only works with 1D

tensor(23)

In [30]:
# transpose

torch.transpose(f, 0,1) # dimensions to transpose

tensor([[2, 5],
        [3, 6]])

In [31]:
# then determinant, then inverse

## Comparison

In [32]:
f > g
g > f
f != g

# etc. returns boolean values

tensor([[True, True],
        [True, True]])

## Special functions

In [33]:
torch.log(f)

torch.exp(f)

k = torch.tensor([[2,3], [6,7]] , dtype=torch.float32)
# for sqrt, sigmmoid, softmax
torch.softmax( k, dim=0)

#relu

torch.relu(k)

tensor([[2., 3.],
        [6., 7.]])

## INPLACE OPERATIONS

In [34]:
# To save memory

m = torch.tensor([[2,3],[3,4]])
n = torch.tensor([[4,5],[6,7]])

m.add_(n) # instead of m + n, replaces value of m itself with the sum without creating new memory space

m.relu_()

# just put operation with _

tensor([[ 6,  8],
        [ 9, 11]])

## Copying tensor

In [35]:
 # if you copy a value into a new variable in vanilla python,
 # and change the values in original variable's value, the other ones change too,
 # as they both point to same address in python

a = torch.rand(2,2)
a

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [36]:
b=a
b

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])

In [37]:
a[0][0] = 20
b

tensor([[20.0000,  0.8238],
        [ 0.5557,  0.9770]])

In [38]:
id(a)

137010707053408

In [39]:
id(b)

137010707053408

In [40]:
# to solve this we use clone
b = a.clone()

print(id(b))
print(id(a))
print(a)
print(b)
a[0][0] = 30
print(a)
print(b)

137010707123088
137010707053408
tensor([[20.0000,  0.8238],
        [ 0.5557,  0.9770]])
tensor([[20.0000,  0.8238],
        [ 0.5557,  0.9770]])
tensor([[30.0000,  0.8238],
        [ 0.5557,  0.9770]])
tensor([[20.0000,  0.8238],
        [ 0.5557,  0.9770]])


# Torch operations on GPU

In [41]:
torch.cuda.is_available()

True

In [42]:
device = torch.device('cuda')

### Everything done till yet, was done in cpu way, now how to do it for gpu

In [43]:
# creating a new tensor on gpu
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [44]:
# moving an existing tensor to GPU
z = a.to(device=device)
z

tensor([[30.0000,  0.8238],
        [ 0.5557,  0.9770]], device='cuda:0')

## NOW MEASURING THE TIME DIFFERENCE AT BIG SCALE, FOR CPU VS GPU

In [49]:
import time
size = 10000

matrix_cpu1 = torch.rand(size , size)
matrix_cpu2 = torch.rand(size , size)

# measuring time
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1 , matrix_cpu2)
cpu_time = time.time() - start_time

print(f"The time on cpu is {cpu_time:.4f}")

matrix_gpu1 = matrix_cpu1.to(device = device)
matrix_gpu2 = matrix_cpu2.to(device = device)

start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)
gpu_time = time.time() - start_time

print(f"The time on gpu is {gpu_time:.4f}")


The time on cpu is 18.5439
The time on gpu is 0.0006


## Reshaping tensors

In [54]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [55]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [56]:
a.flatten() #single dimension

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [58]:
# PERMUTE

b = torch.rand(2,3,4)
b

tensor([[[0.0649, 0.4038, 0.5486, 0.4258],
         [0.7222, 0.2246, 0.3075, 0.5132],
         [0.4423, 0.9050, 0.9142, 0.0124]],

        [[0.2334, 0.8124, 0.1145, 0.9169],
         [0.5305, 0.5444, 0.5816, 0.2842],
         [0.2108, 0.7587, 0.9435, 0.8205]]])

In [62]:
b.permute(2,0,1).shape # replaces the dimensions at 0th:2, 1st:3, 2nd:4

torch.Size([4, 2, 3])

In [65]:
# unsqueeze (done to add a new dimension to fullfill input requirement, like batch)
x = torch.rand(226,226,3)
x.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [66]:
# squeeze (does opposite)
x.squeeze(0).shape

torch.Size([226, 226, 3])

# Moving tensors bw numpy and PyTorch

In [67]:
import numpy as np

In [68]:
x = torch.rand(2,3)
x

tensor([[0.4258, 0.9009, 0.8494],
        [0.1994, 0.2968, 0.4572]])

In [71]:
y = x.numpy()
y

array([[0.4258427 , 0.90093046, 0.8494258 ],
       [0.19941413, 0.29680586, 0.4571622 ]], dtype=float32)

In [72]:
type(y)

numpy.ndarray

In [73]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [75]:
z = torch.from_numpy(c)
type(z)

torch.Tensor